version: '3.8'

volumes:
  postgre_volume:
    driver: local

services:
  postgre:
    container_name: postgre-db-test
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgre_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playground